CXX       := emcc

BIN     := bin
SRC     := src
INCLUDE := include

LIBRARIES   :=
EXECUTABLE  := main


all: $(BIN)/$(EXECUTABLE)
	
run: clean all
	clear
	./$(BIN)/$(EXECUTABLE)

$(BIN)/$(EXECUTABLE): $(SRC)/*/*.cpp  bindings.cpp
					  $(CXX) $(CXX_FLAGS) --bind -I$(INCLUDE) $^ $(LIBRARIES) -o wasm/output.js

clean:
	-rm $(BIN)/*
